version: '3.0'
services:
  frontend:
    image: rasa_fronted:1.0.0
    networks: ['rasa-network']
    ports:
      - "3000:3000"
    depends_on:
      - rasa
  rasa:
    image: rasa_backend:1.0.1
    networks: ['rasa-network']
    ports:
      - "5005:5005"
      - "5055:5055"
#    depends_on:
#      - action-server
#    volumes:
#      - ./:/app
#    command:
#      - run
#  action-server:
#    image: rasa_back_sdk:1.0.0
#    networks: ['rasa-network']
#    ports:
#      - "5055:5055"
#    container_name: action_server
#  action_endpoint:
#    url: http://action_server:5055/webhook
##
#  redis:
#    image: redis:latest
networks: {rasa-network: {}}
#frontend:

#version: '3.0'
#
#services:
#  rasa:
#    image: rasa/rasa:latest-full
#    networks: ['rasa-network']
#    ports:
#    - "5005:5005"
#    volumes:
#    - "./rasa-app-data/:/app/"
#    command:
#    - run
#
#  action_server:
#    image: rasa/rasa-sdk:latest
#    networks: ['rasa-network']
#    ports:
#    - "5055:5055"
#    volumes:
#    - "./rasa-app-data/actions:/app/actions"
#
#  duckling:
#    image: rasa/duckling:latest
#    networks: ['rasa-network']
#    ports:
#    - "8000:8000"
#
#networks: {rasa-network: {}}


#mongo:
#  image: mongo
#  environment:
#    MONGO_INITDB_ROOT_USERNAME: rasa
#    MONGO_INITDB_ROOT_PASSWORD: example
#mongo-express:  # this service is a MongoDB UI, and is optional
#  image: mongo-express
#  ports:
#    - 8081:8081
#  environment:
#    ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
#    ME_CONFIG_MONGODB_ADMINPASSWORD: example
